### ISSUE TITLE
Correct asserts for stock ROM and OTAs can be flashed

### ISSUE THREAD

**Issue by engstk** [TeamWin/android_device_oneplus_onyx#2]
We need this asserts on default.prop to be able to do it:

ro.build.product=ONE
ro.product.device=ONE
ro.display.series=OnePlus X

**Comment by engstk** [comment]
https://github.com/engstk/android_device_oneplus_onyx/commit/54d01ddafd712a715d13694df6299f2dc50404a1

**Comment by Dees-Troy** [comment]
Any reason why you closed this? I just haven't had time yet to review your changes. Ideally, you should submit your changes to gerrit.twrp.me but I don't mind reviewing them here if you have trouble using Gerrit

**Comment by engstk** [comment]
I already uploaded the fix on the gitpull.
https://github.com/TeamWin/android_device_oneplus_onyx/pull/1

I prefer using github, I have no experience in gerrit sorry.
